# docker compose up -d
# docker exec -it postgres-monolith psql -U admin -d postgres -c "CREATE DATABASE \"chaincue-real-estate-db\";"
# docker exec -it chaincue-real-estate-redis redis-cli -a redis -c "FLUSHALL"

version: '3.9'
services:
  chaincue-real-estate-postgres:
    container_name: chaincue-real-estate-postgres
    image: postgres:16.0
    environment:
      POSTGRES_DB: chaincue-real-estate-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - chaincue-real-estate-network

networks:
  chaincue-real-estate-network:
    driver: bridge
    name: chaincue-real-estate-network