class AwsS3Urls:
    URLFrontImage1 = "https://images.chaincuet.com/logos/mansion1.jpeg"
    URLFrontImage2 = "https://images.chaincuet.com/logos/mansion2.jpg"
    URLFrontImage3 = "https://images.chaincuet.com/logos/mansion3.jpg"
    URLFrontImage4 = "https://images.chaincuet.com/logos/mansion4.jpg"
    URLFrontImage5 = "https://images.chaincuet.com/logos/mansion5.jpg"
    URLFrontImage6 = "https://images.chaincuet.com/logos/mansion7.jpeg"
    URL1 = "https://images.chaincuet.com/real-estate/apartment10.jpeg"
    URL2 = "https://images.chaincuet.com/real-estate/apartment11.jpg"
    URL3 = "https://images.chaincuet.com/real-estate/apartment12.jpg"
    URL4 = "https://images.chaincuet.com/real-estate/apartment13.jpg"
    URL5 = "https://images.chaincuet.com/real-estate/apartment14.jpg"
    URL6 = "https://images.chaincuet.com/real-estate/apartment15.jpg"
