# Generated by Django 5.1.4 on 2024-12-20 14:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'house_images',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('number_rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('price', models.CharField(max_length=255)),
                ('src', models.CharField(max_length=255)),
                ('sold', models.BooleanField(default=False)),
                ('house_types', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('images', models.ManyToManyField(blank=True, related_name='houses', to='house.houseimage')),
            ],
            options={
                'db_table': 'houses',
            },
        ),
    ]
